[versions]
kelvin = "2.0.173"
prometheus = "1.8.0"
jackson3-security-override = "3.2.3"
netty = "4.2.18.Final"

[libraries]
kelvin-server = { module = "no.nav.aap.kelvin:server", version.ref = "kelvin" }

# Metrics
prometheus-metrics-core = { module = "io.prometheus:prometheus-metrics-core", version.ref = "prometheus" }

# Netty (constraint override)
netty-common = { module = "io.netty:netty-common", version.ref = "netty" }

# Jackson 3.x (constraint override for CVE-2026-54512)
jackson-core3 = { module = "tools.jackson.core:jackson-core", version.ref = "jackson3-security-override" }
jackson-databind3 = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson3-security-override" }
