/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    kotlin("jvm") version "1.9.21"
    application
}
dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("oppslag.app.AppKt")
}
repositories {
    mavenCentral()
    maven("https://github-package-registry-mirror.gc.nav.no/cached/maven-release")
}

tasks {
    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions.jvmTarget = "21"
    }
    withType<Test> {
        useJUnitPlatform()
    }
}

