name: tokenless deploy Oppslag til DEV

on:
  push:
    branches: [ main ]

permissions: write-all

env:
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/aap/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: test app:buildFatJar --continue --no-daemon --configuration-cache

      - uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: test
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login GAR
        uses: nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: aap

      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-dev:
    needs: [ build ]
    name: Deploy (dev-gcp)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yml
          PRINT_PAYLOAD: true

